# SPDX-FileCopyrightText: 2024 Vladimir Rusinov
# SPDX-License-Identifier: Apache-2.0
---
extends: default
rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
