# SPDX-FileCopyrightText: 2022 Vladimir Rusinov
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "string_ends_with"
version = "1.0.0"
authors = ["Vladimir Rusinov <vladimir.rusinov@gmail.com>"]
edition = "2018"

[dependencies]
