# SPDX-FileCopyrightText: 2025 Vladimir Rusinov <vladimir.rusinov@gmail.com>
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tic_tac_toe_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
